name: dir_chatgnn_tolokers
sweep_config:
  entity: 
  method: bayes
  metric: {goal: maximize, name: val_mean}
  parameters:
    dataset: {value: tolokers}
    loglevel: {value: error}
    model: {value: dirgnn}
    dir_conv: {value: chatgnn}
    post_transform: {value: true}
    layer_norm: {value: true}
    initial_dropout: {value: false}
    n_runs: {value: 1}
    dir_alpha: 
      values: [0, 0.5, 1]
    dropout:
      values: [0.5, 0.6]
    hidden_size:
      values: [64, 96]
    num_layers:
      values: [2, 3, 4, 5, 6, 7, 8]
    lr:
      values: [0.005, 0.01]
    weight_decay:
      values: [0.0001, 0.0005]
  project: 
