name: dir_gcn_chameleon
sweep_config:
  entity: 
  method: bayes
  metric: {goal: maximize, name: val_mean}
  parameters:
    dataset: {value: chameleon}
    loglevel: {value: error}
    model: {value: dirgnn}
    dir_conv: {value: gcn}
    n_runs: {value: 1}
    jk_mode: {value: "max"}
    layer_norm: {value: true}
    dropout:
      values: [0, 0.5]
    hidden_size:
      values: [64, 128, 256, 512]
    lr:
      values: [0.005, 0.01]
    dir_alpha:
      values: [0, 0.5, 1]
    num_layers:
      values: [2, 4, 6, 8, 10]
    weight_decay:
      values: [0.0001, 0.0005]
  project: 
