name: dirgcn_wisconsin
sweep_config:
  entity: 
  method: bayes
  metric: {goal: maximize, name: val_mean}
  parameters:
    dataset: {value: wisconsin}
    dir_alpha:
      values: [0, 0.5, 1]
    dropout: {value: 0.5}
    hidden_size:
      values: [128, 256]
    loglevel: {value: error}
    lr:
      values: [0.01, 0.005]
    model: {value: dirgcn}
    n_runs: {value: 3}
    num_layers:
      values: [2, 3, 4, 5]
    weight_decay:
      values: [0.0001, 0.0005]
  project: 
