name: mlp_cora
sweep_config:
  entity: 
  method: bayes
  metric: {goal: maximize, name: val_mean}
  parameters:
    dataset: {value: cora}
    dropout: {value: 0.5}
    hidden_size:
      values: [32, 64, 128, 256, 512]
    loglevel: {value: error}
    lr:
      values: [0.005, 0.01]
    model: {value: mlp}
    n_runs: {value: 3}
    num_layers:
      values: [2, 3, 4, 5]
    weight_decay:
      values: [0.0001, 0.0005]
  project: 
