name: gcn2_citeseer
sweep_config:
  entity: 
  method: bayes
  metric: {goal: maximize, name: val_mean}
  parameters:
    alpha_gcn2:
      values: [0.1, 0.2, 0.3, 0.4, 0.5]
    dataset: {value: citeseer}
    dropout: {value: 0.5}
    hidden_size:
      values: [16, 32, 64]
    loglevel: {value: error}
    lr:
      values: [0.005, 0.01]
    model: {value: gcn2}
    n_runs: {value: 3}
    num_layers:
      values: [2, 3, 4, 5]
    theta_gcn2:
      values: [0.5, 1, 1.5]
    weight_decay:
      values: [0.0001, 0.0005]
  project: 
