name: gcn_tolokers
sweep_config:
  entity: 
  method: grid
  metric: {goal: maximize, name: val_mean}
  parameters:
    dataset: {value: tolokers}
    dropout: {value: 0.5}
    hidden_size:
      values: [64, 96]
    loglevel: {value: error}
    lr:
      values: [0.005, 0.01]
    model: {value: gcn}
    n_runs: {value: 3}
    num_layers:
      values: [2, 3, 4, 5, 6, 7, 8]
    weight_decay:
      values: [0.0001, 0.0005]
  project: 
