name: gcn_wisconsin
sweep_config:
  entity: 
  method: grid
  metric: {goal: maximize, name: val_mean}
  parameters:
    dataset: {value: wisconsin}
    dropout: {value: 0.5}
    hidden_size:
      values: [128, 256]
    loglevel: {value: error}
    lr:
      values: [0.01, 0.005]
    model: {value: gcn}
    n_runs: {value: 3}
    num_layers:
      values: [2, 3, 4, 5]
    weight_decay:
      values: [0.0001, 0.0005]
  project: 
