name: gatv2res_cornell
sweep_config:
  entity: 
  method: bayes
  metric: {goal: maximize, name: val_mean}
  parameters:
    dataset: {value: cornell}
    dropout: {value: 0.5}
    activation: {value: elu}
    hidden_size:
      values: [64, 128]
    loglevel: {value: error}
    lr:
      values: [0.005, 0.01]
    model: {value: gatv2res}
    n_runs: {value: 3}
    num_layers:
      values: [2, 4, 6, 8, 10]
    weight_decay:
      values: [0.0001, 0.0005]
    n_heads:
      values: [4, 8]
    alpha:
      values: [0.1, 0.2, 0.4]
  project: 
