name: graphsage_cornell
sweep_config:
  entity: 
  method: grid
  metric: {goal: maximize, name: val_mean}
  parameters:
    dataset: {value: cornell}
    dropout: {value: 0.5}
    hidden_size:
      values: [64, 128]
    loglevel: {value: error}
    lr:
      values: [0.005, 0.01]
    model: {value: graphsage}
    n_runs: {value: 3}
    num_layers:
      values: [2, 4, 6, 8, 10]
    weight_decay:
      values: [0.0001, 0.0005]
  project: 
